import type { Metadata } from "next";
import "./globals.css";
import { NavbarDinamico } from "@/components/navbar-dinamico";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body      >
        <NavbarDinamico/>
        {children}
      </body>
    </html>
  );
}
